// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAGC3WQ9FWo02toXCNW3_B5RAMqa_YaNg',
    appId: '1:434389745062:web:9a0919701df1d3f036e367',
    messagingSenderId: '434389745062',
    projectId: 'fir-4ed6c',
    authDomain: 'fir-4ed6c.firebaseapp.com',
    storageBucket: 'fir-4ed6c.appspot.com',
    measurementId: 'G-58WJEZSCFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhJiEcHPf3cZYUE4C5d6xGzA6jyhUxsCQ',
    appId: '1:434389745062:android:5540c48c3e1b189036e367',
    messagingSenderId: '434389745062',
    projectId: 'fir-4ed6c',
    storageBucket: 'fir-4ed6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHl3RCsMFMRkEs0nBQDCDUvwTupO9qZwE',
    appId: '1:434389745062:ios:fb3799d4cc0a5a4936e367',
    messagingSenderId: '434389745062',
    projectId: 'fir-4ed6c',
    storageBucket: 'fir-4ed6c.appspot.com',
    iosClientId: '434389745062-u0i12n1ee8nk1qto6ickkdl7j1evlg9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHl3RCsMFMRkEs0nBQDCDUvwTupO9qZwE',
    appId: '1:434389745062:ios:a5be78730ba438e936e367',
    messagingSenderId: '434389745062',
    projectId: 'fir-4ed6c',
    storageBucket: 'fir-4ed6c.appspot.com',
    iosClientId: '434389745062-a3jh9rqgilcmnb5gusogumdkt1q5s7lt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
